config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticate do
    # post 'companies/search', to: 'companies#search'
    # get 'companies/search', to: 'companies#search'
    # get 'companies/export', to: 'companies#export', format: %w[csv email_list]
    # post 'companies/export', to: 'companies#export', format: %w[txt]
    resources :companies do
      resources :addresses
      resources :contacts
      collection do
        get 'search'
        post 'search'
        get 'export', to: 'companies#export', format: %w[csv email_list]
        post 'export', to: 'companies#export', format: %w[txt]
      end
    end

    resources :plans do
      get 'search', on: :collection
      get 'new_on_date/:date', to: 'plans#new_on_date', on: :collection
      get 'new_for_company/:company_id', to: 'plans#new_for_company', on: :collection
      post 'status/:id', to: 'plans#set_status', on: :collection
      post 'date/:id', to: 'plans#set_date', on: :collection
    end
    resources :addresses do
      get 'search', on: :collection
      post 'search', on: :collection
      get 'all', on: :collection
    end

    resources :contacts do
      collection do
        get :search, :all
        post :search
      end
    end

    root to: 'welcome#index'

    resources :users do
      collection do
        post 'search' => 'users#search'
        get 'search' => 'users#search'
      end
      member do
        post :create
        patch :update
        get :new, :index, :show
        delete :destroy
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :company
  validates_presence_of :name, :lastname

  def self.contacts_by_params(params)
    where_sql = []
    where_sql << " ((name like '%#{params[:name]}%') or (lastname like '%#{params[:name]}%'))  " unless ["", nil, []].include? params[:name]
    where_sql << "email like '%#{params[:email]}%' " unless ["", nil, []].include? params[:email]
    where_sql << "phone like '%#{params[:phone]}%' " unless ["", nil, []].include? params[:phone]
    Contact.where(where_sql.join(" and ")).order("#{params[:sort] || "name"} #{params[:order] || "DESC"}")
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update delete destroy]
  before_action :set_company, only: %i[create new index show edit update delete destroy]

  rescue_from Pagy::OverflowError, with: :redirect_to_last_page

  before_action :validate_view_rigths, only: %i[index search all show]
  before_action :validate_delete_rigths, only: %i[destroy]
  before_action :validate_new_rigths, only: %i[new]
  before_action :validate_edit_rigths, only: %i[edit]

  # GET /contacts or /contacts.json
  def index
    @pagy, @contacts = pagy @contacts = @company.contacts.all
  end

  def search
    respond_to do |format|
      format.html do
        @pagy, @contacts = pagy Contact.contacts_by_params(params), items: params[:limit]
        @pagy.vars[:params].merge!(params.permit(:name, :email, :phone, :search, :page,
                                                 :authenticity_token).to_h)
        render :all
      end
      format.json do
        @pagy, @contacts = pagy Contact.contacts_by_params(params), items: params[:limit]
      end
    end
  end

  # GET /contacts/1 or /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = @company.contacts.new
  end

  # GET /contacts/1/edit
  def edit; end

  def all
    respond_to do |format|
      format.html do
        @pagy, @contacts = pagy Contact.contacts_by_params(params), items: params[:limit]
        @pagy.vars[:params].clear
        render :all
      end
      format.json do
        @pagy, @contacts = pagy Contact.contacts_by_params(params), items: params[:limit]
      end
    end
  end

  # POST /contacts or /contacts.json
  def create
    @contact = @company.contacts.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html do
          redirect_to request.referrer
          flash[:success] = "Contact was successfully created."
        end
        format.js { redirect_to request.referrer, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html do
          redirect_to request.referrer
          flash[:success] = "Contact was successfully updated."
        end
        format.js { render :update, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.js
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to company_contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def redirect_to_last_page(exception)
    redirect_to url_for(page: exception.pagy.last),
                alert: "Page ##{params[:page]} is overflowing. Showing page #{exception.pagy.last} instead."
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:company_id])
  end

  def set_contact
    set_company
    @contact = @company.contacts.find(params[:id])
  end

  def validate_view_rigths
    return if LocalRigths.validate(Current.user.rights, "Contact", "View")
    redirect_to(main_app.root_path, alert: "You are not permitted to view this page")
  end

  def validate_delete_rigths
    return if LocalRigths.validate(Current.user.rights, "Contact", "Delete")
    redirect_to(request.referrer, alert: "You are not permitted to view this page")
  end

  def validate_edit_rigths
    return if LocalRigths.validate(Current.user.rights, "Contact", "Edit")
    redirect_to(main_app.root_path, alert: "You are not permitted to view this page")
  end

  def validate_new_rigths
    return if LocalRigths.validate(Current.user.rights, "Contact", "New")
    redirect_to(main_app.root_path, alert: "You are not permitted to view this page")
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:name, :lastname, :email, :phone, :jobposition, :company_id)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_all_contact_actions.erb
<div class="pull-right action-buttons">    
    <%= link_to '<span class="far fa-edit fa-lg"></span>'.html_safe, edit_company_contact_path(id: ct.id,company_id: ct.company_id ), title: "Edit", data: { no_turbolink: true },:remote=> true , "data-toggle" => "modal", "data-target" => "#modal-window" %>    
    <%= link_to '<span class="far fa-trash-alt fa-lg"></span>'.html_safe, company_contact_path(id: ct.id,company_id: ct.company_id ), method: :delete, title: 'Destroy', data: { confirm: 'Are you sure?' } %>    
</div>

app/views/contacts/_all_name.erb
<%=link_to "<span>#{ct.name} #{ct.lastname}</span>".html_safe, edit_company_contact_path(id: ct.id,company_id: ct.company_id), data: { no_turbolink: true } ,:remote=> true , "data-toggle" => "modal", "data-target" => "#modal-window"  %>

app/views/contacts/_company_name.erb
                        <div >
                             <%= link_to "<span class='name'>#{cc.name}</span>".html_safe, cc, title: "#{cc.name}", data: { no_turbolink: true } %>           
                            </div>
                              <% unless cc.note.nil?%>
                                <div class="company_note">
                                <%= cc.note %>    
                                </div>
                                <% end %>

app/views/contacts/_contact_actions.erb
<div class="pull-right action-buttons">        
    
    <%= link_to '<span class="far fa-edit fa-lg"></span>'.html_safe, edit_company_contact_path(id: cc.id), title: "Edit", data: { no_turbolink: true },:remote=> true , "data-toggle" => "modal", "data-target" => "#modal-window" %>    
    <%= link_to '<span class="far fa-trash-alt fa-lg"></span>'.html_safe, company_contact_path(id: cc.id), method: :delete, title: 'Destroy', data: { confirm: 'Are you sure?' } %>   
    
</div>

app/views/contacts/_email.erb
<a href="#" onclick='copyToClipboard("<%="#{cc.email}"%>");'><%="#{cc.email}"%></a>

app/views/contacts/_form.html.erb
<div class="card">
  <% remote ||= false %>
  <%= form_for([@company, @contact], html: { "data-remote": remote }) do |form| %>
    <% if contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>
        <ul>
          <% contact.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="card-header">
    </div>
    <div class="card-body m-1">
      <div class="form-group">
        <div class="field">
          <label for="name">Name</label>
          <%= form.text_field :name, id: "name", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <label for="lastname">Lastname</label>
          <%= form.text_field :lastname, id: "lastname", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <label for="jobposition">Job position</label>
          <%= form.text_field :jobposition, id: "jobposition", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <label for="phone">Phone</label>
          <%= form.text_field :phone, id: "phone", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <label for="email">E-mail</label>
          <%= form.text_field :email, id: "email", class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="card-footer text-muted">
      <div class="actions calendar-heading">
        <%= form.submit class: "btn share-box" %>
      </div>
    </div>
  <% end %>
</div>

app/views/contacts/_name.erb
<%=link_to "<span>#{cc.name} #{cc.lastname}</span>".html_safe, edit_company_contact_path(id: cc.id), data: { no_turbolink: true } ,:remote=> true , "data-toggle" => "modal", "data-target" => "#modal-window"  %>

app/views/contacts/all.html.erb
<script>
  function copyToClipboard(text) {
    const elem = document.createElement('textarea');
    elem.value = text;
    document.body.appendChild(elem);
    elem.select();
    document.execCommand('copy');
    document.body.removeChild(elem);
    toastr.success(text+' copied to clipboard!', '', { closeButton: true, progressBar: true })
  }
  </script>
<div class="card">
  <div class="header">
  <div class="panel-body">
    <form class="form-horizontal" role="form" method="post" action="<%=search_contacts_path %>">      
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="field-custom">
        <div class="row">
          <div class="col-md-15">
            <div class="form-group form-group-sm">
              <div class="col-md-12">
                <input type="text" name="name" class="form-control input-sm" id="exampleInputPassword2"
                  placeholder="name" value="<%= params[:name] || "" %>">
              </div>              
            </div>
            <div class="form-group form-group-sm">
              <div class="col-md-12">
                <input type="text" name="email" class="form-control input-sm" id="exampleInputPassword2"
                  placeholder="e-mail" value="<%= params[:email] || "" %>">
              </div>              
            </div>
          </div>          
          <div class="col-md-15">
            <div class="form-group  form-group-sm">
              <div class="col-md-12">
                <input type="text" name="phone" class="form-control input-sm" id="exampleInputPassword2"
                  placeholder="phone number" value="<%= params[:phone] || "" %>">
              </div>
            </div>
          </div>

        </div>
      </div>
      <div class="text-center">
        <div class="btn-group">
          <button type="submit" class="btn btn-primary btn-lg active" name="search" value="search"
            title="Search">Search</button>
        </div>
      </div>
  </div>
</div>
<div class="card">
  <div class="body">
<div data-turbolinks="false">
  <table class="table table-responsive" id="table-regular" data-toggle="table" data-url="<%="#{search_contacts_path(name: params[:name],email: params[:email],phone: params[:phone],page: params[:page])}"%>"
    data-sortable="true"
    data-page-size="100"    
    data-side-pagination="server"
    data-select-item-name="id[]"
    data-click-to-select="true"    
    data-id-field="id"
    >
    <thead>
      <tr>
        <th data-field="state" data-checkbox="true"></th>                          
        <th data-field="id" data-switchable="false" data-visible="false">ID</th>
                                  <th data-field="name_lastname" data-width="50" data-width-unit="%" >Name</th>  
                                  <th data-field="jobposition" data-width="20" data-width-unit="%">Job position</th>                                
                                  <th data-field="email" data-width="20" data-width-unit="%">E-mail</th>
                                  <th data-field="phone" data-width="20" data-width-unit="%">Phone</th>
                                  <th data-field="company" data-width="20" data-width-unit="%">Company</th>
                                  <th data-field="actions" data-width="20" data-width-unit="%">Actions</th>
      </tr>
    </thead>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>
</div>
</div>
<br>
</div> 

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/contacts/create.js.erb
<% if @contact.errors.blank? %>
    $('#modal-window').modal('hide');
<% else %>
    $("#modal-window .modal-content").html("<%= escape_javascript(render "form", contact: @contact, remote: true) %>");
<% end %>

app/views/contacts/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j(render "form", contact: @contact, remote: true) %>");
$("#modal-window").modal("show");

app/views/contacts/index.html.erb
<script>
  function copyToClipboard(text) {
    const elem = document.createElement('textarea');
    elem.value = text;
    document.body.appendChild(elem);
    elem.select();
    document.execCommand('copy');
    document.body.removeChild(elem);
    toastr.success(text+' copied to clipboard!', '', { closeButton: true, progressBar: true })
  }
  </script>
<div class="card">
  <div class="header">
    <strong>
      <%= "Contacts" %>
    </strong>
    

      <strong>
        <%= " for #{Company.find(params[:company_id]).name}" %>
      </strong>
    

        
  </div>
  <div class="body">
    <div data-turbolinks="false">
      <table class="table table-responsive" id="table-regular" data-toggle="table" data-url="<%="
        #{company_contacts_path(authenticity_token: form_authenticity_token)}"%>"
        data-sortable="true"
        data-page-size="10"
        data-search="true"
        data-side-pagination="client"
        data-select-item-name="id[]"
        data-click-to-select="true"
        data-id-field="id"
        >
        <thead>
          <tr>
            <th data-field="id" data-switchable="false" data-visible="false">ID</th>
            <th data-field="name_lastname" data-width="50" data-width-unit="%">Name</th>
            <th data-field="jobposition" data-width="20" data-width-unit="%">Job position</th>
            <th data-field="email" data-width="20" data-width-unit="%">E-mail</th>
            <th data-field="phone" data-width="20" data-width-unit="%">Phone</th>
            <th data-field="actions" data-width="20" data-width-unit="%">Actions</th>
          </tr>
        </thead>
      </table>
      <%== pagy_bootstrap_nav(@pagy) %>
        <br>
    </div>
  </div>
</div>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/contacts/new.js.erb
$("#modal-window .modal-content").html("<%= escape_javascript(render "form", contact: @contact, remote: true) %>");
$("#modal-window").modal("show");

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company_id %>
</p>

<%= link_to 'Edit', edit_company_contact_path(id: @contact.id) %> |
<%= link_to 'Back', company_contacts_path %>

app/views/contacts/update.js.erb
<% if @contact.errors.blank? %>
    $('#modal-window').modal('hide');
    window.location.reload();
<% else %>
    $("#modal-window .modal-content").html("<%= escape_javascript(render "form", contact: @contact, remote: true) %>");
<% end %>