config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticate do
    # post 'companies/search', to: 'companies#search'
    # get 'companies/search', to: 'companies#search'
    # get 'companies/export', to: 'companies#export', format: %w[csv email_list]
    # post 'companies/export', to: 'companies#export', format: %w[txt]
    resources :companies do
      resources :addresses
      resources :contacts
      collection do
        get 'search'
        post 'search'
        get 'export', to: 'companies#export', format: %w[csv email_list]
        post 'export', to: 'companies#export', format: %w[txt]
      end
    end

    resources :plans do
      get 'search', on: :collection
      get 'new_on_date/:date', to: 'plans#new_on_date', on: :collection
      get 'new_for_company/:company_id', to: 'plans#new_for_company', on: :collection
      post 'status/:id', to: 'plans#set_status', on: :collection
      post 'date/:id', to: 'plans#set_date', on: :collection
    end
    resources :addresses do
      get 'search', on: :collection
      post 'search', on: :collection
      get 'all', on: :collection
    end

    resources :contacts do
      collection do
        get :search, :all
        post :search
      end
    end

    root to: 'welcome#index'

    resources :users do
      collection do
        post 'search' => 'users#search'
        get 'search' => 'users#search'
      end
      member do
        post :create
        patch :update
        get :new, :index, :show
        delete :destroy
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  include Rigths
  include Features

  mattr_accessor :features_list

  INACTIVE = 0
  ACTIVE = 1
  HOT = 2
  ORNOT = 3
  NEW = 4
  DETAL = 5
  OTHER = 10

  STATES = {
    Company::INACTIVE => "Inactive",
    Company::ACTIVE => "Active",
    Company::HOT => "Hot",
    Company::ORNOT => "Old",
    Company::NEW => "New",
    Company::DETAL => "Detal",
    Company::OTHER => "Other",
  }
  has_many :contacts, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :plans, dependent: :destroy
  belongs_to :user, default: -> { Current.user }

  scope :id_in_list, ->(ids) { where("id in (?)", ids) }
  scope :order_by_name, -> { order(name: :asc) }

  validates_presence_of :name, :status

  def main_address
    addresses.where("main = true").first
  end

  def email_list
    contacts.select("email").all.map { |x| x.email }
  end

  def self.search(params)
    where_sql = []

    unless params[:features].nil?
      feature_ids = []
      params[:features].each do |key, value|
        Company.connection.select_all("select c.id from companies c ,json_each(features_hash) as x where x.value = '#{value}' and x.key= '#{key}'").each do |feature|
          feature_ids << feature["id"]
        end
      end
    end

    unless ["", nil, []].include? params[:person]
      person_id = Contact.select("company_id").where("name like '%#{params[:person]}%' or lastname like '%#{params[:person]}%' or email like '%#{params[:person]}%' or REPLACE(phone,' ','') like '%#{params[:person]}%' ").all
    end

    unless ["", nil, []].include? params[:place]
      place_id = Address.select("company_id").where("name like '%#{params[:place]}%' or city like '%#{params[:place]}%' or region like '%#{params[:place]}%' or postcode like '%#{params[:place]}%' or country like '%#{params[:place]}%' ").all
    end
    ids = []
    (ids += feature_ids) unless params[:features].empty?
    (ids += person_id.map(&:company_id)) unless ["", nil, []].include? params[:person]
    (ids += place_id.map(&:company_id)) unless ["", nil, []].include? params[:place]
    where_sql << "name like '%#{params[:name]}%' " unless ["", nil, []].include? params[:name]
    where_sql << "status = #{params[:state]} " unless ["", nil, []].include? params[:state]
    where_sql << "id in (#{ids.uniq.join(",")}) " if (!["", nil,
                                                        []].include? params[:person]) || (!["", nil,
                                                                                            []].include? params[:place]) || !params[:features].empty?
    Company.select("companies.*,x.max_date as max_date").joins("left join (select max(event_date) max_date,company_id from plans group by company_id) x on x.company_id=companies.id ").where(where_sql.join(" and ")).order("#{params[:sort] || "name"} #{params[:order] || "DESC"}")
  end

  def self.find_by_id(company_id)
    Company.find(company_id)
  end

  def self.list_for_select
    Company.all.order_by_name
  end

  def self.list_by_ids(ids)
    Company.id_in_list(ids).order_by_name
  end

  def self.clear_main_for_company
    addresses.update_all main_address: false
  end

  def features_list_
    @features_list = []
    @features_list << Features::Feature.new(name: "pricelist", caption: "Price list", type: "select",
                                            values: %w[Common Imported Own])

    @features_list
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: %i[show edit update destroy]

  before_action :validate_view_rigths, only: %i[index search show]
  before_action :validate_delete_rigths, only: %i[destroy]
  before_action :validate_new_rigths, only: %i[new]
  before_action :validate_edit_rigths, only: %i[edit]

  rescue_from Pagy::OverflowError, with: :redirect_to_last_page

  # GET /companies or /companies.json
  def index
    @features_list = Company.new.features_list_
    params[:features] = {} if params[:features].nil?
    self.params = params.permit!
    @pagy, @companies = pagy Company.search(params), items: params[:limit]
    @pagy.vars[:params].clear
  end

  def search
    @features_list = Company.new.features_list_
    params[:features] = {} if params[:features].nil?
    self.params = params.permit!
    respond_to do |format|
      format.html do
        @pagy, @companies = pagy Company.search(params), items: params[:limit]
        @pagy.vars[:params].merge!(params.permit(:name, :state, :person, :place, :page, :authenticity_token,
                                                 'features': {}).to_h)

        render :index
      end
      format.json do
        @pagy, @companies = pagy Company.search(params), items: params[:limit]
      end
    end
  end

  # GET /companies/1 or /companies/1.json
  def show
    @main_adress = @company.main_address
    @features_list = @company.features_list_
    params[:features] = if @company.features_hash.nil?
        {}
      else
        JSON.parse @company.features_hash
      end
  end

  # GET /companies/new
  def new
    @company = Company.new
    @features_list = @company.features_list_
    params[:features] = if @company.features_hash.nil?
        {}
      else
        JSON.parse @company.features_hash
      end
  end

  # GET /companies/1/edit
  def edit
    @features_list = @company.features_list_
    params[:features] = if @company.features_hash.nil?
        {}
      else
        JSON.parse @company.features_hash
      end
  end

  # POST /companies or /companies.json
  def create
    params[:company][:features_hash] = params[:features].to_json

    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.js { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        @features_list = @company.features_list_
        format.html { render :new, status: :unprocessable_entity }
        format.js
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def export
    params[:features] = {} if params[:features].nil?
    self.params = params.permit!
    respond_to do |format|
      format.text do
        @companies = Company.search(params)
        headers["Content-Disposition"] = "attachment; filename=\"emaillist_#{Time.now.strftime("%Y%m%d_%H%M%S")}.txt\""
        headers["Content-Type"] ||= "text/plain"
        headers["Transfer-Encoding"] ||= "identity"
        render layout: false
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      params[:company][:features_hash] = params[:features].to_json
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.js { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def redirect_to_last_page(exception)
    redirect_to url_for(page: exception.pagy.last),
                alert: "Page ##{params[:page]} is overflowing. Showing page #{exception.pagy.last} instead."
  end

  def validate_view_rigths
    return if LocalRigths.validate(Current.user.rights, "Company", "View")
    redirect_to(main_app.root_path, alert: "You are not permitted to view this page")
  end

  def validate_delete_rigths
    return if LocalRigths.validate(Current.user.rights, "Company", "Delete")
    redirect_to(request.referrer, alert: "You are not permitted to view this page")
  end

  def validate_edit_rigths
    return if LocalRigths.validate(Current.user.rights, "Company", "Edit")
    redirect_to(main_app.root_path, alert: "You are not permitted to view this page")
  end

  def validate_new_rigths
    return if LocalRigths.validate(Current.user.rights, "Company", "New")
    redirect_to(main_app.root_path, alert: "You are not permitted to view this page")
  end

  def set_company
    @company = Company.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def company_params
    params.require(:company).permit(:name, :status, :note, :user_id, :features_hash)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
    include Pagy::Frontend
    
end

app/views/companies/_index_actions.erb
<div class="pull-right action-buttons">        
    <%= link_to '<span class="fas fa-eye fa-lg"></span>'.html_safe, cc, title: "Show", data: { no_turbolink: true } %>           
    <%= link_to '<span class="far fa-edit fa-lg"></span>'.html_safe, edit_company_path(cc), title: "Edit", data: { no_turbolink: true },:remote=> true , "data-toggle" => "modal", "data-target" => "#modal-window" %>    
    <%= link_to '<span class="far fa-trash-alt fa-lg"></span>'.html_safe, cc, method: :delete, title: 'Destroy', data: { confirm: 'Are you sure?' } %>   
    <%= link_to '<span class="fas fa-user-friends fa-lg"></span>'.html_safe, company_contacts_path(cc.id) ,title: "Contacts", data: { no_turbolink: true } %>   
    <%= link_to '<span class="fas fa-building fa-lg"></span>'.html_safe, company_addresses_path(cc.id) ,title: "Addresses", data: { no_turbolink: true } %>   
    <%= link_to '<span class="fas fa-lg fa-clipboard"></span>'.html_safe, plans_url(company: cc.id) ,title: "Tasks", data: { no_turbolink: true } %>   
    <a href="#" onclick='copyToClipboard("<%="#{cc.email_list.join(',')}"%>");'><%='<span class="fas fa-lg fa-at"></span>'.html_safe%></a>    
</div>
<script>
  function copyToClipboard(text) {
    const elem = document.createElement('textarea');
    elem.value = text;
    document.body.appendChild(elem);
    elem.select();
    document.execCommand('copy');
    document.body.removeChild(elem);
    toastr.success(text+' copied to clipboard!', '', { closeButton: true, progressBar: true })
  }
  </script>

app/views/companies/create.js.erb
<% if @company.errors.blank? %>
    $('#modal-window').modal('hide');
<% else %>
    $("#modal-window .modal-content").html("<%= escape_javascript(render "form", company: @company, remote: true) %>");
<% end %>

app/views/companies/index.html.erb
  <div class="card">
    <div class="header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to 'New Company' , new_company_path , class: "nav-link " , :remote=> true , "data-toggle" =>
                "modal","data-target" => "#modal-window" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Export
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to 'E-mail list', "#{export_companies_path(format: 'txt',state: params[:state],selected: params[:selected],name: params[:name],person: params[:person],place:params[:place],sort: params[:sort],order: params[:order],features: params[:features])}", class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </nav>
      <div class="panel-body">
        <form class="form-horizontal form-remove-empty-get-params" role="form" method="post" action="<%= search_companies_path %>">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div class="field-custom">
              <div class="row">
                <div class="col-md-15">
                  <div class="form-group  form-group-sm">
                    <div class="col-md-12">
                      <%= select_tag("state",options_for_select(Company::STATES.to_a.map{|x| [x[1],
                        x[0]]},params["state"]),{prompt: 'status' ,
                        class: "form-control input-sm send-form-after-change" }) %>
                    </div>
                  </div>
                  <div class="form-group form-group-sm">
                    <div class="col-md-12">
                      <input type="text" name="name" class="form-control input-sm" id="exampleInputPassword2"
                        placeholder="name" value="<%= params[:name] || "" %>">
                    </div>
                  </div>
                </div>
                <div class="col-md-15">
                  <div class="form-group  form-group-sm">
                    <div class="col-md-12">
                      <input type="text" name="person" class="form-control input-sm" id="exampleInputPassword2"
                        placeholder="person" value="<%= params[:person] || "" %>">
                    </div>
                  </div>
                  <div class="form-group form-group-sm">
                    <div class="col-md-12">
                      <input type="text" name="place" class="form-control input-sm" id="exampleInputPassword2"
                        placeholder="place" value="<%= params[:place] || "" %>">
                    </div>
                  </div>
                </div>
                <div class="col-md-15">
                <% @features_list.each do |xx| %>
                <div class="form-group form-group-sm">
                  <div class="col-md-12">                    
                      <%= select_tag "features[#{xx.name.to_s}]",  options_for_select( xx.values, selected: params[:features]["#{xx.name.to_s}"] ), { prompt: "#{xx.caption.to_s}" , class: 'form-control', required: false ,id: "features_#{xx.name.to_s}"} %>
                  </div>
                </div>
                <%end%>
                </div>


                <div class="col-md-15">
                <div class="col-md-12">
                  <button type="submit" class="btn btn-primary btn-lg active" name="search" value="search"
                    title="Search">Search</button>
                </div>
              </div>
            </div>
            </div>
      </div>
    </div>
    <div class="body">
      <div data-turbolinks="false">
        <table class="table table-responsive" id="table-regular" data-toggle="table" data-method="post" data-url="<%= "
          #{search_companies_path(state: params[:state], name: params[:name],person:
          params[:person],place:params[:place],page: params[:page],limit: params[:limit],sort: params[:sort],order:
          params[:order],authenticity_token: form_authenticity_token,features: params[:features])}"%>"
          data-page-size="5"
          data-sort-name=<%="#{params[:sort]||'name'}"%>
            data-sort-order=<%="#{params[:order]||'desc'}"%>
              data-side-pagination="server"
              data-select-item-name="id[]" data-click-to-select="true"
              data-id-field="id" data-row-style="rowStyle" data-click-to-select="true" data-icon-size="sm"
              data-id-field="id"
              data-select-item-name="id[]"
              data-cookie = "true"
              data-cookie-id-table = "CompaniesTable"
              data-cookie-expire = "12h"
              >
              <thead>
                <tr>
                  <th data-field="state" data-checkbox="true"></th>
                  <th data-field="id" data-switchable="false" data-visible="false">ID</th>
                  <th data-field="name" data-width="75" data-sortable="true" data-width-unit="%">Company Name</th>
                  <th data-field="created_at" data-width="5" data-width-unit="%" data-sortable="true">Created</th>
                  <th data-field="status" data-width="5" data-width-unit="%">Status</th>
                  <th data-field="max_date" data-sortable="true" data-width="5" data-width-unit="%">Last event</th>
                  <th data-field="actions" data-width="25" data-width-unit="%">Actions</th>
                </tr>
              </thead>
        </table>
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>

    <br>

  </div>
  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

  <script>

    function rowStyle(row, index) {
      console.log(row)
      if (row.status.includes('Active')) {
        return {
          css: {
            'background-color': '#A2D5ABBF'
          }
        }
      } else if (row.status.includes('Hot')) {
        return {
          css: {
            'background-color': '#B20600BF'
          }
        }
      } else if (row.status.includes('Old')) {
        return {
          css: {
            'background-color': '#ECB365BF'
          }
        }
      } else if (row.status.includes('New')) {
        return {
          css: {
            'background-color': '#0093ABBF'
          }
        }
      } else if (row.status.includes('Other')) {
        return {
          css: {
            'background-color': '#cac7c7BF'
          }
        }
      } else if (row.status.includes('Detal')) {
          return {
              css: {
                  'background-color': 'rgba(190,83,25,0.75)'
              }
          }
      }
      else if (row.status.includes('Own')) {
        return {
          css: {
            'background-color': '#FFD124BF'
          }
        }
      }
      else {
        return {
          css: {}
        }
      }

    }
  </script>

app/views/companies/show.html.erb
<script>
function copyToClipboard(text) {
  const elem = document.createElement('textarea');
  elem.value = text;
  document.body.appendChild(elem);
  elem.select();
  document.execCommand('copy');
  document.body.removeChild(elem);
  toastr.success(text+' copied to clipboard!', '', { closeButton: true, progressBar: true })
}
</script>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-7">
      <div class="card">
        <% if @company.own==true %>
        <div class="header bg-own">
          <%else%>
            <div class='<%="header bg-c#{@company.status.to_i}"%>'>
              <%end%>
                                <strong>[<%= @company.id %>]</strong>
                                <strong>
                                  <%= @company.name %>
                                </strong>   
                                
                                <%= link_to '<span class="text_align_r far fa-edit fa-lg"></span>'.html_safe, edit_company_path(@company), title: "Edit", data: { no_turbolink: true },:remote=> true , "data-toggle" => "modal", "data-target" => "#modal-window" %>
                                
                              </div>
                            
                            <div class="body">
                              <% unless @main_adress.nil? %>
                                <table class="table table-striped top-0" style="margin-bottom: 0;">
                                  <tbody>
                                    <tr>
                                      <td class=" title">Name: </td>
                                      <td>
                                        <%=@main_adress.name %>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td class=" title">Street / number : </td>
                                      <td>
                                        <%="#{@main_adress.street}/#{@main_adress.number}"%>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td class=" title">City : </td>
                                      <td>
                                        <%="#{@main_adress.postcode} #{@main_adress.city}"%>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td class=" title">Count : </td>
                                      <td>
                                        <%="#{@main_adress.country}"%>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td class=" title">Region : </td>
                                      <td>
                                        <%="#{@main_adress.region}"%>
                                      </td>
                                    </tr>
                                    <% params[:features].each do |key,value| %>
                                    <tr>
                                      <td class=" title"><%=key.to_s.capitalize%>:</td>
                                      <td>
                                        <%="#{value.to_s}"%>
                                      </td>
                                    </tr>
                                    <%end%>

                                  </tbody>
                                </table>
                                <%end%>
                                <div>
                                  <p>Note:</p>
                                  <p><%=@company.note%> </p>
                                </div>
                            </div>
                            <div class="footer">
                             
                            </div>
                        </div>
                        <div class="card">
                          <div class="header">
                            <strong>Task and plans:</strong>
                          </div>
                          <div class="body">
                            <div data-turbolinks="false">
                              <table class="table table-responsive" id="table-regular" data-toggle="table" data-url="<%=" #{plans_url(company: @company.id)}"%>"
                                data-pagination="true"
                                data-page-size="100"
                                data-page-list="[10,20,50,100,200]"
                                data-search="true"
                                data-show-jump-to="true"
                                data-single-select="true"
                                data-side-pagination="client"
                                data-select-item-name="id[]"
                                data-click-to-select="true"
                                data-id-field="id"
                                >
                                <thead>
                                  <tr>
                                    <th data-field="id" data-switchable="false" data-visible="false">ID</th>
                                    <th data-field="event_date">Date</th>
                                    <th data-field="event_type_s">Type</th>
                                    <th data-field="event_name">Task</th>
                                    <th data-field="event_description">Description</th>
                                    <th data-field="actions">Actions</th>
                                    
                                  </tr>
                                </thead>
                              </table>
                            </div>
                          </div>
                          <div class="footer">                            
                            <%= link_to '<span style="background-color: #AF002A" class="plus fas fa-lg fa-plus modal-button"></span>'.html_safe,
                            "#{plans_url}/new_for_company/#{@company.id}",title: "New task",
                              data: { no_turbolink: true,:remote=> true , "data-toggle" => "modal", "data-target" => "#modal-window" } %>
                          </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                      <div class="card">
                        <div class="header">
                          <strong>Contacts:</strong>
                        </div>
                        <div class="body">
                          <div data-turbolinks="false">
                            <table class="table table-responsive" id="table-regular" data-toggle="table" data-url="<%="
                              #{company_contacts_path(company_id: @company.id)}"%>"
                              data-pagination="true"
                              data-page-size="100"
                              data-page-list="[10,20,50,100,200]"
                              data-search="true"
                              data-show-jump-to="true"
                              data-single-select="true"
                              data-side-pagination="client"
                              data-select-item-name="id[]"
                              data-click-to-select="true"
                              data-id-field="id"
                              >
                              <thead>
                                <tr>                                  
                                  <th data-field="id" data-switchable="false" data-visible="false">ID</th>
                                  <th data-field="name_lastname">Name</th>  
                                  <th data-field="jobposition">Job position</th>                                
                                  <th data-field="email">E-mail</th>
                                  <th data-field="phone">Phone</th>
                                  <th data-field="actions">Actions</th>
                                </tr>
                              </thead>
                            </table>
                          </div>
                        </div>
                        <div class="footer">
                          <%= link_to '<span style="background-color: #AF002A" class="plus fas fa-lg fa-plus modal-button"></span>'.html_safe,
                            new_company_contact_path(company_id: @company.id), title: "New Contact" , data: {
                            no_turbolink: true,:remote=> true , "data-toggle" => "modal", "data-target" =>
                            "#modal-window"} %>
                        </div>
                      </div>
                      <div class="card">
                        <div class="header">
                          <strong>Addresses:</strong>
                        </div>
                        <div class="body">
                          <div data-turbolinks="false">
                            <table class="table table-responsive" id="table-regular" data-toggle="table" data-url="<%="
                              #{company_addresses_path(company_id: @company.id)}"%>"
                              data-pagination="true"
                              data-page-size="100"
                              data-page-list="[10,20,50,100,200]"
                              data-search="true"
                              data-show-jump-to="true"
                              data-single-select="true"
                              data-side-pagination="client"
                              data-select-item-name="id[]"
                              data-click-to-select="true"
                              data-id-field="id"
                              >
                              <thead>
                                <tr>                                  
                                  <th data-field="id" data-switchable="false" data-visible="false">ID</th>
                                  <th data-field="name">Name</th>
                                  <th data-field="street">Street</th>
                                  <th data-field="number">number</th>
                                  <th data-field="city">City</th>
                                  <th data-field="postcode">Postcode</th>
                                  <th data-field="country">Country</th>
                                  <th data-field="region">Region</th>
                                  <th data-field="main">Main</th>
                                  <th data-field="actions">Actions</th>
                                </tr>
                              </thead>
                            </table>
                          </div>
                        </div>
                        <div class="footer">
                          <%= link_to '<span style="background-color: #AF002A" class="plus fas fa-lg fa-plus modal-button"></span>'.html_safe,
                            new_company_address_path(company_id: @company.id), title: "New Address" , data: {
                            no_turbolink: true,:remote=> true , "data-toggle" => "modal", "data-target" =>
                            "#modal-window" } %>
                        </div>
                      </div>
                    </div>
                </div>
            </div>

            <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel"
              aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content"></div>
              </div>
            </div>