config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticate do
    # post 'companies/search', to: 'companies#search'
    # get 'companies/search', to: 'companies#search'
    # get 'companies/export', to: 'companies#export', format: %w[csv email_list]
    # post 'companies/export', to: 'companies#export', format: %w[txt]
    resources :companies do
      resources :addresses
      resources :contacts
      collection do
        get 'search'
        post 'search'
        get 'export', to: 'companies#export', format: %w[csv email_list]
        post 'export', to: 'companies#export', format: %w[txt]
      end
    end

    resources :plans do
      get 'search', on: :collection
      get 'new_on_date/:date', to: 'plans#new_on_date', on: :collection
      get 'new_for_company/:company_id', to: 'plans#new_for_company', on: :collection
      post 'status/:id', to: 'plans#set_status', on: :collection
      post 'date/:id', to: 'plans#set_date', on: :collection
    end
    resources :addresses do
      get 'search', on: :collection
      post 'search', on: :collection
      get 'all', on: :collection
    end

    resources :contacts do
      collection do
        get :search, :all
        post :search
      end
    end

    root to: 'welcome#index'

    resources :users do
      collection do
        post 'search' => 'users#search'
        get 'search' => 'users#search'
      end
      member do
        post :create
        patch :update
        get :new, :index, :show
        delete :destroy
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord
  OTHER = 0
  EMAIL = 1
  PHONE = 2
  OFFER = 3
  INVOICE = 4
  CONTRACT = 5

  TYPES = {
    Plan::OTHER => "Other action",
    Plan::EMAIL => "E-mail",
    Plan::PHONE => "Phone",
    Plan::OFFER => "Offer",
    Plan::INVOICE => "Invoice",
    Plan::CONTRACT => "Contract",
  }

  EVENT = 0
  PLANED = 1
  DONE = 2
  CANCELED = 3

  STATUS = {
    Plan::EVENT => "Event",
    Plan::PLANED => "Planed",
    Plan::DONE => "Done",
    Plan::CANCELED => "Canceled",
  }

  belongs_to :company
  validates_presence_of :event_name, :company_id, :event_date, :event_type

  class << self
    def plans_for_day(date, company_id = nil)
      if LocalRigths.validate(Current.user.rights, "Plan", "View")
        if ["", nil, []].include? company_id
          Plan.where("event_date = ?", date).count
        else
          Plan.where("event_date = ? and company_id =? ", date, company_id).count
        end
      else
        0
      end
    end

    def plans_by_params(params)
      if %w[date company].any? { |i| params.keys.include?(i) }
        sql = []

        sql << "event_date='#{params[:date]}' " if params[:date]
        sql << "company_id='#{params[:company]}' " if params[:company]

        Plan.where(sql.join(" and ")).all
      else
        Plan.all
      end
    end

    def companies_in_month(date)
      Plan.select("id,company_id").where("strftime('%m/%Y',event_date)=strftime('%m/%Y','#{date}')").map { |x| x.company_id }
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[show edit update destroy set_status set_date]
  before_action :set_cache_headers

  before_action :validate_view_rigths, only: %i[index search show]
  before_action :validate_delete_rigths, only: %i[destroy]
  before_action :validate_new_rigths, only: %i[new new_on_date new_for_company]
  before_action :validate_edit_rigths, only: %i[edit]

  # GET /plans or /plans.json
  def index
    @plans = Plan.plans_by_params(params)
  end

  def search
    @plans = Plan.plans_by_params(params)
    render "index"
  end

  # GET /plans/1 or /plans/1.json
  def show; end

  # GET /plans/new
  def new
    @plan = Plan.new
    if params[:date]
      @plan.event_date = params[:date]
    else
      @plan.event_date = DateTime.now.to_date
      params[:date] = DateTime.now.to_date
    end
    @plan.company_id = params[:company] if params[:company]
  end

  def new_on_date
    @plan = Plan.new
    @plan.event_date = params[:date]
    render :new_on_date
  end

  def new_for_company
    @plan = Plan.new
    params[:date] = DateTime.now.to_date
    @plan.company_id = params[:company_id]
    render :new_for_company
  end

  # GET /plans/1/edit
  def edit; end

  # POST /plans or /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html do
          redirect_to request.referrer
          flash[:success] = "Task was successfully created."
        end
        format.js { redirect_to request.referrer, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1 or /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html do
          redirect_to request.referrer
          flash[:success] = "Task was successfully updated."
        end
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1 or /plans/1.json
  def destroy
    @plan.destroy

    respond_to do |format|
      format.html do
        redirect_to request.referrer
        flash[:success] = "Task was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  def set_status
    @plan.status = params[:plan][:status]
    @plan.save!
  end

  def set_date
    unless params[:plan][:event_date].empty?
      @plan.event_date = params[:plan][:event_date]
      @plan.save!
    end
    redirect_to request.referrer
  end

  private

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Mon, 01 Jan 1990 00:00:00 GMT"
  end

  def validate_view_rigths
    return if LocalRigths.validate(Current.user.rights, "Plan", "View")
    redirect_to(main_app.root_path, alert: "You are not permitted to view this page")
  end

  def validate_delete_rigths
    return if LocalRigths.validate(Current.user.rights, "Plan", "Delete")
    redirect_to(request.referrer, alert: "You are not permitted to view this page")
  end

  def validate_edit_rigths
    return if LocalRigths.validate(Current.user.rights, "Plan", "Edit")
    redirect_to(main_app.root_path, alert: "You are not permitted to view this page")
  end

  def validate_new_rigths
    return if LocalRigths.validate(Current.user.rights, "Plan", "New")
    redirect_to(main_app.root_path, alert: "You are not permitted to view this page")
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def plan_params
    params.require(:plan).permit(:event_date, :event_name, :event_description, :status, :event_type, :company_id,
                                 :contact_id, :address_id, :user)
  end
end

app/helpers/plans_helper.rb
module PlansHelper

end

app/views/plans/_company_name.erb
                        <div >
                             <%= link_to "<span class='name'>#{cc.name}</span>".html_safe, cc, title: "#{cc.name}", data: { no_turbolink: true } %>           
                            </div>
                              <% unless cc.note.nil?%>
                                <div class="company_note">
                                <%= cc.note %>    
                                </div>
                                <% end %>

app/views/plans/_form.html.erb
<div class="card">
  <div class="card-header">
    <% if %w[new new_on_date create].include? controller.action_name %>
      <p>New Task</p>
    <% else %>
      <p>Edit Task</p>
    <% end %>
    <% if controller.action_name == "edit" %>
      <%= " #{plan.event_date}" %>
    <% end %>
  </p>
  <% if plan.company_id %>
    <% cc = Company.find_by_id(plan.company_id) %>
    <% if cc.own == true %>
      <p class="bg-own">
      <% else %>
        <p class='<%= "bg-c#{cc.status.to_i}" %>'>
        <% end %>
        <%= cc.name %>
      </p>
    <% end %>
  </div>
  <% remote ||= false %>
  <%= form_for(plan, html: { "data-remote": remote }) do |form| %>
    <div class="card-body m-1">
      <% if plan.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:
          </h2>
          <ul>
            <% plan.errors.each do |error| %>
              <li>
                <%= error.full_message %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div data-turbolinks="false">
        <div class="form-group">
          <div class="field">
            <% if params[:date] || @plan.event_date.present? %>
              <%= form.label :event_date, class: "required" %>
              <%= form.text_field :event_date, value: (params[:date].nil? ?
                                                 form.object.try(:strftime, "%Y-%m-%d") : params[:date].to_date) || @plan.event_date, id: "event_date",
                                               class: "form-control flatpickr" %>
            <% end %>
          </div>
        </div>
        <% unless "edit".include? controller.action_name %>
          <div class="form-group select-company">
            <div class="field">
              <%= form.label :company_id, class: "required" %>
              <%= form.select :company_id, options_for_select(Company.list_for_select.collect { |u| [u.name, u.id] }, selected: plan.company_id), { prompt: "Select" }, { id: "id-select2", required: "true", autofocus: "true",
                                                                                                                                                                          class: "form-control content-search" } %>
            </div>
          </div>
        <% end %>
        <% if ["new_for_company", "edit"].include? controller.action_name %>
          <div class="form-group">
            <div class="field">
              <%= form.label :contact_id %>
              <%= form.select :contact_id,
                              options_for_select(Company.find_by_id(plan.company_id).contacts.collect { |u|
                                ["#{u.name} #{u.lastname}", u.id]
                              }), { prompt: "Select" }, { id: "id-select2", autofocus: "true",
                                                          class: "form-control content-search" } %>
            </div>
          </div>
          <div class="form-group">
            <div class="field">
              <%= form.label :address_id %>
              <%= form.select :address_id,
                              options_for_select(Company.find_by_id(plan.company_id).addresses.all.collect { |u|
                                ["#{u.name}", u.id]
                              }), { prompt: "Select" }, { id: "id-select2", autofocus: "true",
                                                          class: "form-control content-search" } %>
            </div>
          </div>
        <% end %>
        <div class="form-group">
          <div class="field">
            <%= form.label :event_type, class: "required" %>
            <%= form.select :event_type, options_for_select(Plan::TYPES.invert.to_a, selected: plan.event_type), { prompt: "Select" }, { id: "id-select2-types", required: "true",
                                                                                                                                         autofocus: "true", class: "form-control" } %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= form.label :event_name %>
          <%= form.text_field :event_name, id: "even_name", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= form.label :event_description %>
          <%= form.text_area :event_description, :cols => 30, :rows => 10, id: "event_description", class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="card-footer text-muted">
      <div class="actions calendar-heading">
        <% if controller.action_name == "edit" %>
          <%= form.submit "Update task", class: "btn btn-primary" %>
        <% else %>
          <%= form.submit "Add task", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/plans/_index_actions.erb
<div class="pull-right action-buttons">        
    <%= link_to '<span class="fas fa-eye fa-lg"></span>'.html_safe, plan, title: "Show", data: { no_turbolink: true },:remote=> true , "data-toggle" => "modal", "data-target" => "#modal-window" %>           
    <%= link_to '<span class="far fa-edit fa-lg"></span>'.html_safe, edit_plan_path(plan), title: "Edit", data: { no_turbolink: true },:remote=> true , "data-toggle" => "modal", "data-target" => "#modal-window" %>    
    <%= link_to '<span class="far fa-trash-alt fa-lg"></span>'.html_safe, plan, method: :delete, title: 'Destroy', data: { confirm: 'Are you sure?' } %>       
</div>

app/views/plans/_index_date.erb
<div class="pull-right action-buttons">
      <script>
      $(document).ready(function () {
      $('.send-form-after-change').change(function () {
        $(this).parents('form').submit();
    });

    const config =  {
      "enableTime": false,
     "dateFormat": "Y-m-d",
     "minDate": "today"
}
    flatpickr("[class='form-control flatpickr send-form-after-change']", config );
});
      </script>

     <%= form_for (plan), url: "#{plans_url}/date/#{plan.id}",method: :post, remote: true do |form| %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= form.text_field :event_date , value: plan.event_date , id: "event_date" ,class: 'form-control flatpickr send-form-after-change'%>
                            
                            <%end%>
</div>

app/views/plans/_index_status.erb
<div class="pull-right action-buttons">    
      <script>
      $(document).ready(function () {   
      $('.send-form-after-change').change(function () {
        $(this).parents('form').submit();
    });    
}); 
      </script>
      
     <%= form_for (plan), url: "#{plans_url}/status/#{plan.id}",method: :post, remote: true do |form| %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= form.select :status, options_for_select(Plan::STATUS.invert.to_a,selected:plan.status), {prompt: 'Select' },{id: "id-select2-types" , required: 'true' ,autofocus: 'true' , class: 'form-control input-sm send-form-after-change' } %>
                            <%= submit_tag "", :id => 'status',:style => 'display:none' %>
                            <%end%>
</div>

app/views/plans/_show.html.erb
<div class="card">
  <div class="card-header">
    <p>Task: <strong><%=@plan.id%></strong></p>
  </div>
  <div class="card-body m-1">
<p id="notice"><%= notice %></p>

<p>
  <strong>Event date:</strong>
  <%= @plan.event_date %>
</p>
    <%if @plan.company_id %>
    <p>
    <strong>Company:</strong>
    <% cc = Company.find_by_id(@plan.company_id) %>    
    <%=cc.name%>      
    </p>
    <%end%>

    <%if @plan.contact_id %>
    <p>
    <strong>Contact:</strong>
    <% cc = Company.find_by_id(@plan.company_id) %>    
    <% kc = cc.contacts.find_by_id(@plan.contact_id)  %>
    <%="#{kc.name} #{kc.lastname}"%>      
    </p>
    <%end%>

    <%if @plan.address_id %>
    <p>
    <strong>Address:</strong>
    <% cc = Company.find_by_id(@plan.company_id) %>    
    <% ac = cc.addresses.find_by_id(@plan.address_id) %>
    <%="#{ac.name}"%>      
    </p>
    <%end%>




<p>
  <strong>Event name:</strong>
  <%= @plan.event_name %>
</p>

<strong>Description:</strong>
<div class="p-2 px-3 text" id="textField">
  <textarea readonly rows="10">
    <%= @plan.event_description %>
  </textarea>
  
</div>
</div>

app/views/plans/create.js.erb
<% if @plan.errors.blank? %>
    $('#modal-window').modal('hide');
<% else %>
    $("#modal-window .modal-content").html("<%= escape_javascript(render "form", plan: @plan, remote: true) %>");
<% end %>

app/views/plans/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j(render "form", plan: @plan) %>");
flatpickr("[class='form-control flatpickr']", {enableTime: false, dateFormat: "Y-m-d",minDate: "today"})
$("#modal-window").modal("show");

app/views/plans/index.html.erb
<script>
  $(document).ready(function () {
  $('.table-regular').bootstrapTable();
    })
</script>
<div class="card" >
  <div class="header">
    <strong>
      <%= "Plans" %>
    </strong>
    <% if params[:company] %>

      <strong>
        <%= " for #{Company.find_by_id(params[:company]).name}" %>
      </strong>
      <% end %>

        <% if params[:date] %>
          <strong>
            <%= " on #{params[:date]}" %>
          </strong>
          <% end %>
  </div>
  <div class="body" data-turbolinks="false">
    <%= form_tag :plans, method: :get, class: "search" do %>     
     <% if params[:date] %>
     <% d_minus = ((Date.strptime(params[:date],"%Y-%m-%d"))-1).strftime("%Y-%m-%d") %>
     <% d_plus =  ((Date.strptime(params[:date],"%Y-%m-%d"))+1).strftime("%Y-%m-%d") %>
     <%=link_to '<span style="background-color: #AF002A" class="fas fa-lg fa-plus modal-button"></span>'.html_safe, new_plan_path({date:params[:date],company:params[:company]}),title: "New task" , data: { no_turbolink: true,:remote=> true , "data-toggle" => "modal","data-target" => "#modal-window" } %>
     <%=link_to '<span style="background-color: #AF002A" class="fas fa-lg fa-arrow-left modal-button"></span>'.html_safe , search_plans_url(:date => d_minus , :company => params[:company], :search => "") %>
     <%=link_to '<span style="background-color: #AF002A" class="fas fa-lg fa-arrow-right modal-button"</span>'.html_safe, search_plans_url(:date => d_plus , :company => params[:company], :search => "")  %>
     <% end %>     
    <% end %>

    <table class="table table-responsive" id="table-regular" data-toggle="table" data-url="<%="#{plans_url(date:params["date"],company: params[:company])}"%>"
      data-pagination="true"
      data-page-size="100"
      data-page-list="[10,20,50,100,200]"
      data-search="true"
      data-show-jump-to="true"
      data-single-select="true"
      data-side-pagination="client"
      data-select-item-name="id[]"
      data-click-to-select="true"
      data-id-field="id"
      >
      <thead>
        <tr>
          <th data-field="id" data-switchable="false" data-visible="false">ID</th>
          <th data-field="event_date">Date</th>
          <th data-field="company" data-sortable="true">Company</th>
          <th data-field="event_type_s">Type</th>
          <th data-field="event_name">Task</th>
          <th data-field="event_description">Description</th>
          <th data-field="created_at">Created</th>
          <th data-field="actions">Actions</th>
          <th data-field="status" data-width="10" data-width-unit="%">Status</th>
        </tr>
      </thead>
    </table>
  </div>
</div>
     <br>        
          <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content"></div>
            </div>
          </div>

app/views/plans/new.js.erb
$("#modal-window .modal-content").html("<%= escape_javascript(render "form", plan: @plan, remote: true) %>");
flatpickr("[class='form-control flatpickr']", {enableTime: false, dateFormat: "Y-m-d",minDate: "today"})
$("#modal-window").modal("show");

app/views/plans/new_for_company.js.erb
$("#modal-window .modal-content").html("<%= escape_javascript(render "form", plan: @plan, company_id: @plan.company_id, remote: true) %>");
$('.select-company').prop('hidden', true);
flatpickr("[class='form-control flatpickr']", {enableTime: false, dateFormat: "Y-m-d",minDate: "today"})
$("#modal-window").modal("show");

app/views/plans/new_on_date.js.erb
$("#modal-window .modal-content").html("<%= escape_javascript(render "form", plan: @plan, remote: true) %>");
flatpickr("[class='form-control flatpickr']", {enableTime: false, dateFormat: "Y-m-d",minDate: "today"})
$("#modal-window").modal("show");

app/views/plans/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j(render 'show', plan: @plan) %>");
flatpickr("[class='form-control flatpickr']", {enableTime: false, dateFormat: "Y-m-d",minDate: "today"})
$("#modal-window").modal("show");