config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticate do
    # post 'companies/search', to: 'companies#search'
    # get 'companies/search', to: 'companies#search'
    # get 'companies/export', to: 'companies#export', format: %w[csv email_list]
    # post 'companies/export', to: 'companies#export', format: %w[txt]
    resources :companies do
      resources :addresses
      resources :contacts
      collection do
        get 'search'
        post 'search'
        get 'export', to: 'companies#export', format: %w[csv email_list]
        post 'export', to: 'companies#export', format: %w[txt]
      end
    end

    resources :plans do
      get 'search', on: :collection
      get 'new_on_date/:date', to: 'plans#new_on_date', on: :collection
      get 'new_for_company/:company_id', to: 'plans#new_for_company', on: :collection
      post 'status/:id', to: 'plans#set_status', on: :collection
      post 'date/:id', to: 'plans#set_date', on: :collection
    end
    resources :addresses do
      get 'search', on: :collection
      post 'search', on: :collection
      get 'all', on: :collection
    end

    resources :contacts do
      collection do
        get :search, :all
        post :search
      end
    end

    root to: 'welcome#index'

    resources :users do
      collection do
        post 'search' => 'users#search'
        get 'search' => 'users#search'
      end
      member do
        post :create
        patch :update
        get :new, :index, :show
        delete :destroy
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Crmm</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': false %>
<%= stylesheet_link_tag "my", media: "all", 'data-turbolinks-track': false %>
<%= stylesheet_pack_tag "application", media: "all", 'data-turbolinks-track': false %>
<%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
<%= javascript_pack_tag "main", "data-turbolinks" => false, defer: false %>
</head>

<body>

  <div class="container-fluid">
    <% if user_signed_in? %>
    <div class="row flex-nowrap">
      <div class="col-auto px-0">
        <%= toastr_flash %>
        <div id="sidebar" class="collapse collapse-horizontal show border-end">
            <div id="sidebar-nav" class="list-group border-0 rounded-0 text-sm-start min-vh-100">
              <div class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"></div>
              <a href="<%= root_path %>" class="list-group-item border-end-0 d-inline-block text-truncate" data-turbolinks=false data-bs-parent="#sidebar"><i class="fas fa-lg fa-clipboard"></i> <span>Calendar</span></a>
              <a href="<%= companies_path %>" class="list-group-item border-end-0 d-inline-block text-truncate" data-turbolinks=false data-bs-parent="#sidebar"><i class="fas fa-lg fa-address-book"></i> <span id="c_company">Companies</span> </a>
              <a href="<%= all_contacts_path %>" class="list-group-item border-end-0 d-inline-block text-truncate" data-turbolinks=false data-bs-parent="#sidebar"><i class="fas fa-user-friends fa-lg"></i> <span>Contacts</span></a>
              <a href="<%= all_addresses_path %>" class="list-group-item border-end-0 d-inline-block text-truncate" data-turbolinks=false data-bs-parent="#sidebar" ><i class="fas fa-building fa-lg"></i> <span>Addresses</span></a>
              <% if LocalRigths.validate(Current.user.rights, "User", "Admin") %>
              <a href="<%= users_path %>" class="list-group-item border-end-0 d-inline-block text-truncate" data-turbolinks=false data-bs-parent="#sidebar" ><i class="fas fa-user-tie fa-lg"></i> <span>Users</span></a>
              <% end %>
              <div class="list-group-item border-end-0 d-inline-block text-truncate">
                <span class="user_name company_note">User     </span>
                <p class="user_name dt-user-avatar" style="background-color:<%= ColorX.with_google("#{Current.user.lastname}#{Current.user.name}") %>"><%= "#{(Current.user.name[0] || "empty").capitalize}#{(Current.user.lastname[0] || "empty").capitalize}" %></p>
                <div class="user_logout"><%= link_to '<span class="fas fa-lg fa-door-closed company_note"></span>'.html_safe, destroy_user_session_path, method: :delete, title: "Logout" %>
                  </div>
              </div>

            </div>
        </div>

    </div>
    <% end %>
       <main class="col ps-md-2 pt-2">

          <%= yield %>

      </main>
    </div>

</div>


 </body>

</html>